name: Python
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  utf64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Test
        working-directory: ./utf64/py
        run: make test
