name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  utf64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./utf64/rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./utf64/rust
      run: cargo test --verbose
